version: '3.8'


services:
  web:
    build: ./disptacher
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn disptacher.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./disptacher:/usr/src/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - redis
      - db

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - 80:80
    depends_on:
      - web

  celery:
    build: ./disptacher
    command: celery -A disptacher worker -l info
    volumes:
      - ./disptacher:/usr/src/app
    depends_on:
      - redis
      - web
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  flower:
    build: ./disptacher
    command: celery -A disptacher flower --loglevel=info
    ports:
      - 5555:5555
    depends_on:
      - web
      - redis
      - celery
      - db


volumes:
  static_volume:
  media_volume:
  postgres_data:

networks:
  netone:
    driver: bridge
